server/website/website/tasks/async_tasks.py, server/website/website/views.py
Although we have max/min limits in the GPRGD training session, it may
lose some precisions. e.g. 0.99..99 >= 1.0 may be True on the scaled data,
when we inversely transform the scaled data, the different becomes much larger
and cannot be ignored. Here we check the range on the original data
directly, and make sure the recommended config lies within the range
=> Fix min/max

server/website/website/views.py
It seems that Django has some bugs when change USE_TZ to False to support timezone-aware datetimes. A simple fix is to change the timezone after reading datetime from the database, and show the correct time in the web view.
=> fix timezone

server/analysis/preprocessing.py
Previously, the method total_dummies in the preprocessing module's DummyEncoder class depended on the DummyEncoder having been fit with a nonzero number of categorical (i.e. >= 3 values) features.  When there are no categorical features, the correct thing to do is return 0. Instead, the current code in master will raise an AttributeError, because calling OneHotEncoder.fit(...) with no categorical features results in n_values_ remaining undefined.
=> Fix dummy encoder so that it does when there are no categorical features.

server/analysis/constraints.py, server/analysis/preprocessing.py
In #177, I only cleaned up one instance where the dummy encoder / constraint helper depend on the OneHotEncoder having by fit with at least 1 categorical variable.  This PR completely fixes these dependencies by either removing them or checking that there is at least 1 categorical variable before relying on them.
For example, in the dummy encoder's inverse_transform, if there are no categorical variables, then the function immediately returns the input matrix (as it never got transformed to begin with). Otherwise, it will perform the actual inverse transform logic.
Tested it by running the service locally, uploading data to the tuning session, and seeing that the celery jobs for recommending the new configuration all succeed.
=> Fix dummy encoder (#175) for real.

client/driver/LatencyUDF.py, client/driver/fabfile.py, server/website/tests/test_parser.py, server/website/website/parser/base.py
Currently, we test OtterTune on Postgres for throughput target objective.  The way we get the throughput is calculating changes between 'pg_stat_database.xact_commit' in metric_before and metric_after files, and divides the change by the observation time. We define the metric for throughput as follows. 
https://github.com/cmu-db/ottertune/blob/87c356655a4030123d4eec8b72453d4c12e49937/server/website/website/parser/postgres.py#L68-L70
However, it becomes a problem when we do not have the related metric in metric files for some target objectives. e.g. when we want to get the latency, it's better to have  the start_time and end_time of the transaction/query, and then we can measure the latency as its time interval.  But Postgres does not have internal metric like that. 
In this PR, we fix the …
=> add support for user defined target objective

client/driver/fabfile.py, client/driver/upload_batch.py, server/website/website/models.py, server/website/website/templates/edit_session.html, server/website/website/templates/session.html
(1) When running `fab run_loops` in the client side, you can save the data in `save_path` by calling `save_dbms_result` function.  When you start a new OtterTune server, you can upload these data as training data by using this script, or calling `upload_batch` in the fab file. 
(2) target_objective is needed for both tuning and non-tuning session.
=> add script for uploading training data

server/website/tests/test_tasks.py, server/website/website/models.py, server/website/website/tasks/async_tasks.py, server/website/website/tasks/periodic_tasks.py
Delete workloads when all the corresponding results are deleted. 
In the tuning task, its workload is mapped to one of the existing workloads in the training data, which are updated when running periodic tasks.
Partially fix #104
=> fix workload

server/website/website/tasks/async_tasks.py
If hardware memory is smaller than the max value of memory-related tuning knobs, set the max value as memory size.
=> fix max val

server/website/website/tasks/async_tasks.py
Tensorflow get broken if we use the training data points as starting points for GPRGD. We add a small bias for the starting points. GPR_EPS default value is 0.001.  if the starting point is X_max, we minus a small bias to make sure it is within the range.
=> fix starting points.

client/driver/fabfile.py
This is the issue running latest oltpbench code, the root cause is that [this commit](https://github.com/oltpbenchmark/oltpbench/commit/d8ad0a35da6d34ec9902a1589a198225b68fb299#diff-ddceeebf3cc1804f8af91035d0ecf597L743) by removed the original words in the log.
I found the projects under cmu-db are interdependent. There are some of my suggestions:
- Don't match lines in the log file. For example, use subprocess or threads to monitor the states of the tasks.
- Version control of the indepedent projects such as oltpbench and the projects which depend on these only rely on the released version. 
- Cross projects CI. Might be tricky and also costy(Everytime A has a commit, not only trigger A's CI, but also trigger B(who has dependency on A under cmu-db unbrella)'s CI, not sure github could …
=> Bugfix for _ready_to_shut_down_controller in fabfile.py

server/website/website/management/commands/dumpknob.py, server/website/website/management/commands/dumpknobtunability.py, server/website/website/management/commands/loadknob.py, server/website/website/management/commands/loadknobtunability.py, server/website/website/management/commands/resetwebsite.py, server/website/website/management/commands/stopcelery.py, server/website/website/models.py
- dump session knob to json
- load json, and modify session knobs
- dump and reset website
- load website
usage: 
`python manage.py dumpknob UPLOAD_CODE`
`python manage.py loadknob UPLOAD_CODE`
`python manage.py resetwebsite`
I have done some tests manually to make sure the behaviour is correct.
=> dump and load session knob tunability

server/website/website/set_default_knobs.py
During running workload, postgres throws exception when the knob work_mem is too small. So I propose to set the minval of memory and storage knobs larger, propotional to the hardware capacity.
Also, temp_buffers in postgres is per session, like work_mem.
=> set default minval of knob according to hardware

client/driver/configs/postgres_base.conf, client/driver/driver_config.json, client/driver/fabfile.py
- warmup_iterations: run workload but does not upload result
- sleep_time: after restart database, wait a few minutes
- user can define basic database config
- allow longer restart time (by default, if restart does not finish in 1 minute, it fails)
- explicitly use fast mode for restart, which performs a checkpoint before shutdown
- start the database before reloading the database, otherwise it could fail
- move pd_datadir to driver_conf
=> achieve stable performance and fix bugs

server/website/website/models.py
I also have a list of 70 postgres knobs with correct min/max.
=> change knob catelog when changing session knob tunability

client/driver/fabfile.py, client/driver/oracleScripts/restartOracle.sh, server/website/website/views.py
Fixed ottertune so that when the database crashes on restart, the system regards it as if it had observed the worst throughput seen so far. This allows the machine learning to continue even if the knobs get too large.
=> Handling Database Restart Error

server/website/website/management/commands/startcelery.py, server/website/website/settings/common.py, server/website/website/utils.py, server/website/website/views.py
This is a further attempt to address the celery error which Sebastian still encounters. I think of 4 possible causes for this error:
- Celery is not running before running a tuning task (this type of error is fixed in the previous PR)
- Celery dies when it is running a tuning task (this type of error is not considered in the previous PR)
- For some reason, Celery can never start. 
- Celery is running, but rabbitmq server is not running, so Celery cannot work
*I fixed the second kind of error in this PR*: 
- set `CELERY_ACKS_LATE=True`, so that an incomplete task is still in the queue for retrying. Without this option, when celery is killed, the running task is lost forever.
- every time the client pings the server for results, I check the Celery status and restart Celery if it is down.
- …
=> Check celery on each request for result

server/website/website/static/js/timeline.js
Results table links would get messed up with >1 metric selected.
This was because the way the server sent the result data didn't match the way the client received it.
=> Fixed results table links

server/website/website/utils.py
The aggregate_data method assumes the knob/metric JSON data stored in the [Knob|Metric|Pipeline]Data.data field is sorted which is sometimes violated and causing this error:
```
Traceback (most recent call last):
File "/usr/local/lib/python3.6/dist-packages/celery/app/trace.py", line 240, in trace_task
R = retval = fun(*args, **kwargs)
File "/usr/local/lib/python3.6/dist-packages/celery/app/trace.py", line 438, in __protected_call__
return self.run(*args, **kwargs)
File "/app/website/website/tasks/async_tasks.py", line 939, in configuration_recommendation
pipeline_metrics = combine_workload(target_data)
File "/app/website/website/tasks/async_tasks.py", line 775, in combine_workload
y_columnlabels, target_data['y_columnlabels'])
Exception: ('The workload and target data should have …
```
=> Sort aggregated matrix columns by knob/metric name

server/website/website/admin.py, server/website/website/settings/constants.py, server/website/website/tasks/periodic_tasks.py
Changes:
- By default, the knob identification task now uses the set of target objectives used to tune a particular workload as the output `y` instead of the pruned metrics.
- Added option `KNOB_IDENT_USE_PRUNED_METRICS` to constants.py. When enabled, pruned metrics are also included in the output `y` in the knob identification task. (It's disabled by default).
- Further reduced the number of metrics included as features when computing the workload characterization tasks by additionally filtering out non-unique columns and binning the metrics by deciles before removing constant/non-unique columns.
- Reversed the ordering in a couple of our admin views so newer objects show up first.
=> Background task improvements

server/website/website/tasks/async_tasks.py
- no longer terminating search when there is a large difference in expected value and observed value.
- do not search lowerbound when the min_val is smaller than 10
=> fix knob_range_search lowerbound

server/website/website/db/base/parser.py, server/website/website/settings/constants.py, server/website/website/tasks/async_tasks.py, server/website/website/tasks/periodic_tasks.py, server/website/website/utils.py, server/website/website/views.py
- prune metrics for DDPG:
I think the right way to go is to use a small set of metrics. Otherwise, DDPG can hardly to learn. Therefore, I pick dba_hist_sys_time_model, which can represent the workload and only has 31 metrics.
- clean up convert_dbms_metrics: 
remove unused base_metric_data; rename metric_data to numeric_metric_data; use all metric_data instead of numeric_metric_data to calculate target objectives.
- fix invalid results handling bug:
check if the last_conf is None before copying that to the knob file.
=> clean metrics for DDPG
